name: ducktourguide
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ^3.5.4
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  geolocator: ^14.0.1
  flutter_tts: ^4.2.2
  http: ^1.3.0
  flutter_map: ^8.1.0
  latlong2: ^0.9.1
  geocoding: ^3.0.0
  appwrite: ^14.0.0
  excel: ^4.0.6
  flutter_web_auth_2: ^3.1.2
  flutter_local_notifications: ^17.2.1  # 更新到最新版本

  shared_preferences: ^2.2.2
  flutter_background_service: ^5.1.0
  flutter_background_service_android: ^6.3.0
  url_launcher: ^6.2.5
dependency_overrides:
  flutter_web_auth_2: ^4.1.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/img/attractions/
    - assets/data/attractions.xlsx
    - assets/img/attractions/模具工程系.png
    - assets/img/attractions/電子工程系.png
    - assets/img/attractions/高雄科技大學.png